### ISSUE TITLE
Does it support `concave polygon` or `polygon with holes`?

### ISSUE THREAD

**Issue by finscn** [ironwallaby/delaunay#11]
Does this lib support `concave polygon` or `polygon with holes`?

**Comment by ironwallaby** [comment]
This library doesn't support triangulating polygons at all! It is designed for finding the Delaunay triangulation of a set of points. (This is the first step in triangulating a polygon, but there are additional steps afterwards that are presently out of scope for the library.)

I'd be happy to review any PRs adding this functionality, but do not plan to add it myself at this time.

Sorry!
