### ISSUE TITLE
Please tag your release

### ISSUE THREAD

**Issue by russenreaktor** [ironwallaby/delaunay#7]
https://github.com/ironwallaby/delaunay/releases
according to https://github.com/ironwallaby/delaunay/blob/master/package.json ;)

**Comment by ironwallaby** [comment]
Can you explain why one would do this? That is, it's an additional expenditure of effort and discipline--what are the returns it provides?

**Comment by russenreaktor** [comment]
for somebody (like me) who wants to put a version number in his bower.json and be sure his project will still work after you do changes on your main branch 

Now:

    "dependencies": {
        "delaunay-fast": "git@github.com:ironwallaby/delaunay.git"
    },

If you you will tag the release

    "dependencies": {
        "delaunay-fast": "git@github.com:ironwallaby/delaunay.git#~1.0.1"
    },

**Comment by ironwallaby** [comment]
I thought this is why I pushed changes to NPM? Or is bower entirely package-manager agnostic? (If so, I suppose that's reason enough ;p )

**Comment by aureooms** [comment]
[jspm](http://jspm.io/), [duo](https://github.com/duojs/duo), [component](https://github.com/componentjs/component), and [bower](https://github.com/bower/bower) are using git tags.

**Comment by ironwallaby** [comment]
Hot. I should really start using something other than NPM, then.

Anyway, I'm convinced. Tagging now, and I'll do my best to remember to tag in the future. (I'm not going to go back and tag past versions unless somebody buys be a bottle of Scotch, though.)
