### ISSUE TITLE
Delaunay creates overlapping triangles

### ISSUE THREAD

**Issue by mley** [ironwallaby/delaunay#8]
The delaunay library creates overlapping triangles in some cases.
Steps to reproduce:

var points = [
  [50.726723,7.057675],
  [50.726886,7.056291],
  [50.727253,7.05776],
  [50.727518,7.056366],
  [50.727885,7.057632]
];
var triangles = Delaunay.triangulate(points);

triangles contains now: [3,1,4,0,3,4,1,0,4,3,2,4,0,2,3]

Here is an image
![delaunay_triangles_borked](https://cloud.githubusercontent.com/assets/7995757/11095720/ac6b0ffa-8896-11e5-894d-929b081c3677.png)

**Comment by ironwallaby** [comment]
Eek. That ain't right. It might take me a bit to fix this one, since the bug probably isn't trivial...

**Comment by mley** [comment]
Thanks for looking into it.

I found a workaround for me. When I multiply the values with 100000 before triangulating, then the result looks ok.

var points = [[5072672,705768],[5072689,705629],[5072725,705776],[5072752,705637],[5072789,705763]];

My guess would be, that is is some kind of float rounding problem. But I haven't looked in detail in the code.

**Comment by ironwallaby** [comment]
Yup, looks like that's it: this is a precision issue. Using the algorithm we're using, I don't think this can be fixed, but as you found the work-around is simple.

I haven't checked if other algorithms (like the optimal O(n log n) divide-and-conquer algorithm) exhibit the same issue, but they're pretty overkill... if you need that kind of performance, you shouldn't be using JS. So it'll likely be a long time before I get to it.

**Comment by mley** [comment]
Ok. Thanks for the reply. We can live with the work-around. 

We are using the algorithm for geo-coordinates, which looks like a reasonable use for such an algorithm. Perhaps you can add a sentence on the project description, that the algorithm produces wrong output when the the input values have a lot of decimal places.

**Comment by ironwallaby** [comment]
One thing to beware of in that use case is that this library handles triangulation for a 2D planar surface, while the earth is a 2D spherical surface. I imagine it is possible to define a Delaunay triangulation for that (where each line is defined as a great circle, say), but it requires more math chops than I have.

In any case, if you restrict yourself to a small segment of the globe at a time and avoid the poles, you shouldn't have any issues!

I have also added a brief note on precision to the README. Thanks!
